-- MySQL Script generated by MySQL Workbench
-- Wed Mar 13 19:48:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema foro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema foro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foro` DEFAULT CHARACTER SET utf8 ;
USE `foro` ;

-- -----------------------------------------------------
-- Table `foro`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foro`.`usuario` (
  `idUsuario` INT NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foro`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foro`.`comentario` (
  `idComentario` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `texto` VARCHAR(3000) NOT NULL,
  `imagen` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `foro`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foro`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foro`.`publicacion` (
  `idPublicacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `idComentario` INT NOT NULL,
  PRIMARY KEY (`idPublicacion`),
  INDEX `fk_idComentario_idx` (`idComentario` ASC),
  CONSTRAINT `fk_idComentario`
    FOREIGN KEY (`idComentario`)
    REFERENCES `foro`.`comentario` (`idComentario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
