-- MySQL Script generated by MySQL Workbench
-- Thu Mar 14 19:06:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema foro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema foro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foro` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `foro` ;

-- -----------------------------------------------------
-- Table `foro`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foro`.`Usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nickname` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Avatar` VARCHAR(45) NULL,
  PRIMARY KEY (`IdUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `foro`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foro`.`Publicacion` (
  `IdPublicacion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`IdPublicacion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `foro`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foro`.`Comentario` (
  `IdComentario` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Texto` VARCHAR(3000) NOT NULL,
  `Imagen` VARCHAR(45) NULL,
  `IdUsuario` INT NOT NULL,
  `IdPublicacion` INT NOT NULL,
  PRIMARY KEY (`IdComentario`),
  INDEX `idUsuario_idx` (`IdUsuario` ASC),
  INDEX `fk_idPublicacion_idx` (`IdPublicacion` ASC),
  CONSTRAINT `fk_idUsuario`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `foro`.`Usuario` (`IdUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_idPublicacion`
    FOREIGN KEY (`IdPublicacion`)
    REFERENCES `foro`.`Publicacion` (`IdPublicacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
